name: Default Build Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  run_build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello Build started!"
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Build test-depend with SHA
        run: bhavik-patel24/test-depend@c1ac5a95472a38b1dd790309aa36fbbe1cb9f712

      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Run Binary
        run: ./bkp-test
