name: Pull Request Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  run_pull_job:
    name: run pull job
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
