name: Default Build Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  run_build_job:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
    steps:
      - name: my-step
        run: echo "Hello Build started!"
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
